### ISSUE TITLE
how to auto restart when i kill the child process ?

### ISSUE THREAD

**Issue by wacdev** [ccqpein/supervisor-rs#2]
as title

**Comment by ccqpein** [comment]
you can add the `posthook` feature and add the same name of your child process. 

for example: your file (child name) is `demo.yml`. 

```yml
command: something
hooks:
  - posthook: start demo
```

the after you stop the child, it will start child again.
